version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/the-product
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-client
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: 'create mysql database'
          command: mysql -h 127.0.0.1 -u root -e "create database the_product;"
      - run: yarn build
      - run: yarn test:lint
      - run: yarn migrate --url="mysql://root@localhost/the_product"
      - run:
          name: 'yarn test:unit'
          command: yarn test:unit --ci --coverage --runInBand --verbose --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: yarn test:e2e
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit


