version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/the-product
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-client
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: 'create mysql database'
          command: mysql -h 127.0.0.1 -u root -e "create database the_product_db;"
      - run: yarn build
      - run: yarn test:lint
      - run: yarn migrate --url="mysql://root@localhost/the_product_db"
      - run:
          name: 'yarn test:unit'
          command: yarn test:unit --ci --coverage --runInBand --verbose
          environment:
            APP_MYSQL_URL: "mysql://root@localhost/the_product_db"
      - run:
            name: yarn test:e2e
            command: yarn test:e2e:ci
            environment:
                APP_MYSQL_URL: "mysql://root@localhost/the_product_db"
  deploy:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/the-product
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli==1.15.32
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn deploy-all
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
